spring.application.name=dormex-marketplace
app.dataFolder=src/main/resources/data
app.uploadDir=src/main/resources/uploads
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=dormex.marketplace@gmail.com
spring.mail.password=qxlmntdtgsjdemxv
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
